# Generated by Django 4.2 on 2024-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='settings')),
                ('subtitle', models.TextField(max_length=500)),
                ('call_us', models.CharField(max_length=25)),
                ('emails_us', models.TextField(max_length=50)),
                ('emails', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
