# Generated by Django 4.2 on 2024-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo_brand',
            field=models.ImageField(default='12:00:00', upload_to='settings'),
            preserve_default=False,
        ),
    ]
